
import java.awt.Font;
import java.awt.GraphicsEnvironment;

import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author My Fucking PC
 */
public class FontFrame extends javax.swing.JFrame {

    JTextArea txtWorkplace = null;
    String fontName="";
    int fontStyle, fontSize;
    /**
     * Creates new form Font
     */
    public FontFrame(JTextArea txtWorkplace) {
        initComponents();
        Font[] fontList = new Font[]{};
        fontList = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
        for (int i = 0; i < fontList.length; i++) {
            cbbFont.addItem(fontList[i].getFontName());
        }
        fontName = (String) cbbFont.getSelectedItem();
        fontSize = (int) spinnerSize.getValue();
        fontStyle = (int) cbbStyle.getSelectedIndex();
        lblTest.setFont(new Font(fontName,fontSize,fontSize));
        this.txtWorkplace = txtWorkplace;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbFont = new javax.swing.JComboBox<>();
        spinnerSize = new javax.swing.JSpinner();
        cbbStyle = new javax.swing.JComboBox<>();
        lblTest = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Font");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Font size");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Font style");

        cbbFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFontActionPerformed(evt);
            }
        });
        cbbFont.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbFontPropertyChange(evt);
            }
        });

        spinnerSize.setValue(13);
        spinnerSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSizeStateChanged(evt);
            }
        });
        spinnerSize.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinnerSizePropertyChange(evt);
            }
        });

        cbbStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plain", "Bold", "Italic", "Bold Italic" }));
        cbbStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbStyleActionPerformed(evt);
            }
        });
        cbbStyle.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbbStylePropertyChange(evt);
            }
        });

        lblTest.setText("Font test");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbFont, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTest)
                    .addComponent(btnOK))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(lblTest)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbFontPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbFontPropertyChange
        
    }//GEN-LAST:event_cbbFontPropertyChange

    private void spinnerSizePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinnerSizePropertyChange
        
    }//GEN-LAST:event_spinnerSizePropertyChange

    private void cbbStylePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbbStylePropertyChange
        
    }//GEN-LAST:event_cbbStylePropertyChange

    private void cbbFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFontActionPerformed
        fontName = (String) cbbFont.getSelectedItem();
        lblTest.setFont(new Font(fontName,fontSize,fontSize));
    }//GEN-LAST:event_cbbFontActionPerformed

    private void cbbStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbStyleActionPerformed
        fontStyle = (int) cbbStyle.getSelectedIndex();
        lblTest.setFont(new Font(fontName,fontSize,fontSize));
    }//GEN-LAST:event_cbbStyleActionPerformed

    private void spinnerSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSizeStateChanged
        fontSize = (int) spinnerSize.getValue();
        lblTest.setFont(new Font(fontName,fontSize,fontSize));
    }//GEN-LAST:event_spinnerSizeStateChanged

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String changeFontText = txtWorkplace.getSelectedText();
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbbFont;
    private javax.swing.JComboBox<String> cbbStyle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTest;
    private javax.swing.JSpinner spinnerSize;
    // End of variables declaration//GEN-END:variables
}
